export const USER_TYPE = {
  HOST: 'HOST',
  RENTER: 'RENTER',
};

export const RESERVATION_STATUS = {
  NEW: 'NEW',
  ACCEPTED: 'ACCEPTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETE: 'COMPLETE',
  DECLINED: 'DECLINED',
  CANCELED: 'CANCELED',
};
